{
    "name": "FlexSys Digital Menu",
    "summary": "Smart white-label digital menu for Odoo POS",
    "version": "19.0.1.0.8",
    "category": "Point of Sale/Restaurant",
    "author": "FlexSys",
    "website": "https://flexsyssa.com",
    "support": "info@flexsyssa.com",
    "license": "OPL-1",
    "depends": ["product", "point_of_sale", "stock", "web"],
    "data": [
        "security/security.xml",
        "security/ir.model.access.csv",
        "data/default_theme.xml",
        "views/menu_theme_views.xml",
        "views/menu_schedule_views.xml",
        "views/menu_category_views.xml",
        "views/menu_product_views.xml",
        "views/menu_views.xml",
        "views/product_template_views.xml",
        "wizard/setup_wizard_views.xml",
        "views/menu_navigation.xml",
        "views/public_templates.xml",
    ],
    "assets": {},
    "application": True,
    "installable": True,
}
