{
    'name': 'FlexSys',
    'version': '19.0.1.1.0',
    'summary': 'FlexSys Smart Cafe and Restaurant Operations, QR Ordering, Branch Management and POS Integration',
    'category': 'Point of Sale',
    'author': 'FlexSys',
    'depends': [
        'base',
        'web',
        'product',
        'point_of_sale',
        'mail',
        'portal',
        'auth_signup',
    ],
    'data': [
        'security/qtcafe_security.xml',
        'security/ir.model.access.csv',
        'data/sequence.xml',
        'data/qr_menu_category_data.xml',
        'views/qtcafe_qr_order_views.xml',
        'views/qtcafe_qr_printer_config_views.xml',
        'views/qtcafe_qr_menu_templates.xml',
        'views/routing_settings_views.xml',
        'views/qr_table_views.xml',
        'views/manager_account_views.xml',
        'views/pos_config_views.xml',
        'views/pos_config_branch_views.xml',
        'views/res_config_settings_views.xml',
        'views/menu.xml',
        'views/qtcafe_settings_views.xml',
    ],
    'assets': {
        'web.assets_frontend': [
            'flexsys_operations/static/src/scss/qr_menu.scss',
            'flexsys_operations/static/src/js/qr_menu.js',
            'flexsys_operations/static/src/js/manager_dashboard.js',
        ],
        'web.assets_backend': [
            'flexsys_operations/static/src/scss/qr_dashboard.scss',
            'flexsys_operations/static/src/js/qr_dashboard.js',
        ],
        'point_of_sale._assets_pos': [
            'flexsys_operations/static/src/js/pos_qr_alert.js',
            'flexsys_operations/static/src/js/pos_qr_load_to_pos.js',
            'flexsys_operations/static/src/xml/pos_qr_load_to_pos.xml',
            'flexsys_operations/static/src/js/pos_qr_cancel_sync.js',
        ],
    },
    'application': True,
    'installable': True,
    'license': 'LGPL-3',
}