{
    'name': 'FlexSys Platform',
    'version': '19.0.4.0.0',
    'summary': 'Platform identity, application registry, Mission Control, shared design system, and Operations (self-order, POS, execution stations) for FlexSys',
    'category': 'Productivity',
    'author': 'FlexSys',
    'license': 'LGPL-3',
    'depends': [
        'base',
        'web',
        'mail',
        'product',
        'point_of_sale',
        'portal',
        'auth_signup',
    ],
    'data': [
        'security/operations_security.xml',
        'security/ir.model.access.csv',
        'data/platform_data.xml',
        'data/platform_application.xml',
        'data/sequence.xml',
        'data/menu_category_data.xml',
        'views/platform_views.xml',
        'views/platform_templates.xml',
        'views/operations_order_views.xml',
        'views/operations_printer_views.xml',
        'views/self_order_templates.xml',
        'views/routing_settings_views.xml',
        'views/operation_table_views.xml',
        'views/manager_account_views.xml',
        'views/pos_config_views.xml',
        'views/pos_config_branch_views.xml',
        'views/res_config_settings_views.xml',
        'views/menu.xml',
        'views/operations_settings_views.xml',
        'views/execution_engine_views.xml',
        'views/station_ticket_report.xml',
    ],
    'assets': {
        'web.assets_frontend': [
            'flexsys_platform/static/src/css/platform.css',
            'flexsys_platform/static/src/js/command_palette.js',
            'flexsys_platform/static/src/js/platform_ui.js',
            'flexsys_platform/static/src/scss/self_order.scss',
            'flexsys_platform/static/src/js/self_order.js',
            'flexsys_platform/static/src/js/manager_dashboard.js',
        ],
        'web.assets_backend': [
            'flexsys_platform/static/src/css/platform.css',
            'flexsys_platform/static/src/scss/operations_dashboard.scss',
            'flexsys_platform/static/src/js/operations_dashboard.js',
        ],
        'point_of_sale._assets_pos': [
            'flexsys_platform/static/src/js/pos_order_alert.js',
            'flexsys_platform/static/src/js/pos_order_load.js',
            'flexsys_platform/static/src/xml/pos_order_load.xml',
            'flexsys_platform/static/src/js/pos_order_cancel_sync.js',
        ],
    },
    'application': True,
    'installable': True,
}
